/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControleUsuario;
import Modelo.ModeloUsuario;
import static Visao.Venda.venda;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Dell
 */
public class Home extends javax.swing.JFrame {

    ModeloUsuario modeloUsuario = new ModeloUsuario();
    ControleUsuario controleUsuario = new ControleUsuario();
    public static int idUser;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public void idUsuario() throws SQLException {
        modeloUsuario.setNome_login(LblUsuario.getText());
        idUser = controleUsuario.buscarIdDoUsuario(modeloUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelUsuar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelTipoUser = new javax.swing.JLabel();
        LblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelHora = new javax.swing.JLabel();
        LabelData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuUsuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        RelatorioVendas = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        telaSobre = new javax.swing.JMenuItem();
        MenuOpcao = new javax.swing.JMenu();
        MenuOpcaoSair = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        TrocaDeUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Home");
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        LabelUsuar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelTipoUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelTipoUser.setText("usuario");

        LblUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblUsuario.setText("nome usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Hora");

        LabelHora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelHora.setText("horas");

        LabelData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelData.setText("date");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Data");

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        MenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_sign-up_49622.png"))); // NOI18N
        MenuCadastro.setText("Cadastros");
        MenuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCadastro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_clients_43573.png"))); // NOI18N
        jMenuItem2.setText("Cliente");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuCadastro.add(jMenuItem2);
        MenuCadastro.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_suppliers_54265.png"))); // NOI18N
        jMenuItem1.setText("Fornecedor");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuCadastro.add(jMenuItem1);
        MenuCadastro.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_pack-2_56046.png"))); // NOI18N
        jMenuItem4.setText("Produto");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuCadastro.add(jMenuItem4);
        MenuCadastro.add(jSeparator3);

        MenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MenuUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user_285655.png"))); // NOI18N
        MenuUsuario.setText("Usuário");
        MenuUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuUsuario.setEnabled(false);
        MenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuUsuario);

        Menu.add(MenuCadastro);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_Sales-by-Payment-Method-rep_49616.png"))); // NOI18N
        jMenu1.setText("Vendas");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_note_1086667.png"))); // NOI18N
        jMenuItem6.setText("Formulário");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        Menu.add(jMenu1);

        MenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_reports_49615.png"))); // NOI18N
        MenuRelatorio.setText("Relatórios");
        MenuRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuRelatorio.setEnabled(false);
        MenuRelatorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        RelatorioVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        RelatorioVendas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_sales-report_49617.png"))); // NOI18N
        RelatorioVendas.setText("Vendas");
        RelatorioVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioVendasActionPerformed(evt);
            }
        });
        MenuRelatorio.add(RelatorioVendas);

        Menu.add(MenuRelatorio);

        MenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_Male-User-Help_49594.png"))); // NOI18N
        MenuAjuda.setText("Ajuda");
        MenuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuAjuda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        telaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        telaSobre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        telaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_free-18_463010.png"))); // NOI18N
        telaSobre.setText("Sobre");
        telaSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaSobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(telaSobre);

        Menu.add(MenuAjuda);

        MenuOpcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if__88ui_2303204.png"))); // NOI18N
        MenuOpcao.setText("Opções");
        MenuOpcao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuOpcao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        MenuOpcaoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuOpcaoSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MenuOpcaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_support_477135.png"))); // NOI18N
        MenuOpcaoSair.setText("Trocar usuário");
        MenuOpcaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuOpcaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpcaoSairActionPerformed(evt);
            }
        });
        MenuOpcao.add(MenuOpcaoSair);
        MenuOpcao.add(jSeparator5);

        TrocaDeUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        TrocaDeUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TrocaDeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/if_free-09_463017.png"))); // NOI18N
        TrocaDeUser.setText("Sair");
        TrocaDeUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TrocaDeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrocaDeUserActionPerformed(evt);
            }
        });
        MenuOpcao.add(TrocaDeUser);

        Menu.add(MenuOpcao);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 858, Short.MAX_VALUE)
                        .addComponent(LabelUsuar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(LabelTipoUser)
                                    .addComponent(jLabel3))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTipoUser)
                            .addComponent(LblUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LabelHora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelData)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUsuar))
        );

        setSize(new java.awt.Dimension(888, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linhas abaixo substituem as labels data pela data do sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        LabelData.setText(formatador.format(data));

        Timer time = new Timer(1000, new hora());
        time.start();
    }//GEN-LAST:event_formWindowActivated

    private void MenuOpcaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpcaoSairActionPerformed
        // exibe uma caixa de diálogo
        if (venda == 1) {
            JOptionPane.showMessageDialog(rootPane, "Primeiro feche o formulário de vendas!");
        } else {
            int trocar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja trocar de usuário?", "Atenção", JOptionPane.YES_NO_OPTION);
            try {
                if (trocar == JOptionPane.YES_OPTION) {
                    Login l = new Login();
                    l.setVisible(true);
                    dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_MenuOpcaoSairActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String x = Produto.x;
        try {
            if (x == null) {
                Produto p = new Produto();
                p.setVisible(true);
                jDesktopPane1.add(p);
            } else {
                JOptionPane.showMessageDialog(rootPane, "A janela de cadastro de produtos já está aberta!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void MenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuarioActionPerformed
        // TODO add your handling code here:
        String x = TelaUser.x;
        try {
            if (x == null) {
                TelaUser t = new TelaUser();
                t.setVisible(true);
                jDesktopPane1.add(t);
            } else {
                JOptionPane.showMessageDialog(rootPane, "A janela de cadastro de usuários já está aberta!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuUsuarioActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        int venda = Venda.venda;
        try {
            if (venda == 0) {
                idUsuario();
                Venda v = new Venda();
                v.setVisible(true);
                jDesktopPane1.add(v);
            } else {
                JOptionPane.showMessageDialog(rootPane, "A janela formulário de vendas já está aberta!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String y = Clientes.y;
        try {
            if (y == null) {
                Clientes c = new Clientes();
                c.setVisible(true);
                jDesktopPane1.add(c);
            } else {
                JOptionPane.showMessageDialog(rootPane, "A janela de cadastro de clientes já está aberta!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void telaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaSobreActionPerformed
        // TODO add your handling code here:
        String y = Sobre.y;

        if (y == null) {
            Sobre t = new Sobre();
            t.setVisible(true);
            jDesktopPane1.add(t);
        } else {
            JOptionPane.showMessageDialog(rootPane, "A janela sobre já está aberta!");
        }

    }//GEN-LAST:event_telaSobreActionPerformed

    private void TrocaDeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrocaDeUserActionPerformed
        // TODO add your handling code here:
        if (venda == 1) {
            JOptionPane.showMessageDialog(rootPane, "Primeiro feche o formulário de vendas!");
        } else {
            int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
            // a condição abaixo valida a escolha do usuário
            if (sair == JOptionPane.YES_OPTION)//se a opção que o usuario for sim
            {
                System.exit(0);//sai do sistem
            }
        }
    }//GEN-LAST:event_TrocaDeUserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String y = Fornecedor.y;
        if (y == null) {
            Fornecedor f = new Fornecedor();
            f.setVisible(true);
            jDesktopPane1.add(f);
        } else {
            JOptionPane.showMessageDialog(rootPane, "A janela de cadastro de fornecedores já está aberta!");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void RelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioVendasActionPerformed
        // TODO add your handling code here:
        PesquisaVendas pv = new PesquisaVendas();
        pv.setVisible(true);
        jDesktopPane1.add(pv);

    }//GEN-LAST:event_RelatorioVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelHora;
    public static javax.swing.JLabel LabelTipoUser;
    public static javax.swing.JLabel LabelUsuar;
    public static javax.swing.JLabel LblUsuario;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuOpcao;
    private javax.swing.JMenuItem MenuOpcaoSair;
    public static javax.swing.JMenu MenuRelatorio;
    public static javax.swing.JMenuItem MenuUsuario;
    private javax.swing.JMenuItem RelatorioVendas;
    private javax.swing.JMenuItem TrocaDeUser;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem telaSobre;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            LabelHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
}
